create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null
);

create table if not exists public.prize_pool (
  id bigint primary key default 1,
  first_prize_total integer not null default 0,
  second_prize_total integer not null default 0,
  third_prize_total integer not null default 0,
  first_prize_remaining integer not null default 0,
  second_prize_remaining integer not null default 0,
  third_prize_remaining integer not null default 0,
  team_mapping jsonb,
  is_configured boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.spin_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  spin_count integer not null default 0,
  has_won boolean not null default false,
  prize_tier text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.admins enable row level security;
alter table public.prize_pool enable row level security;
alter table public.spin_sessions enable row level security;

insert into public.prize_pool (id, is_configured, team_mapping)
values (1, false, null)
on conflict (id) do nothing;

create or replace function public.spin_lottery(p_session_id text, p_team_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pool public.prize_pool%rowtype;
  v_session public.spin_sessions%rowtype;
  v_prize_tier text := 'none';
  v_remaining integer := 0;
  v_spins_used integer;
begin
  insert into public.spin_sessions (session_id)
  values (p_session_id)
  on conflict (session_id) do nothing;

  select *
  into v_session
  from public.spin_sessions
  where session_id = p_session_id
  for update;

  if v_session.has_won then
    return jsonb_build_object('status', 403, 'error', '已中獎，本次工作階段已結束。');
  end if;

  if v_session.spin_count >= 3 then
    return jsonb_build_object('status', 403, 'error', '抽獎次數已用完。');
  end if;

  select *
  into v_pool
  from public.prize_pool
  where id = 1
  for update;

  if not found or not v_pool.is_configured then
    return jsonb_build_object('status', 400, 'error', '管理員尚未設定獎池。');
  end if;

  select coalesce(item->>'prize', 'none')
  into v_prize_tier
  from jsonb_array_elements(coalesce(v_pool.team_mapping, '[]'::jsonb)) as item
  where item->>'teamCode' = p_team_code
  limit 1;

  v_prize_tier := coalesce(v_prize_tier, 'none');

  if v_prize_tier = 'first' then
    v_remaining := v_pool.first_prize_remaining;
  elsif v_prize_tier = 'second' then
    v_remaining := v_pool.second_prize_remaining;
  elsif v_prize_tier = 'third' then
    v_remaining := v_pool.third_prize_remaining;
  else
    v_remaining := 0;
  end if;

  if v_prize_tier in ('first', 'second', 'third') and v_remaining > 0 then
    if v_prize_tier = 'first' then
      update public.prize_pool
      set first_prize_remaining = first_prize_remaining - 1,
          updated_at = now()
      where id = 1;
    elsif v_prize_tier = 'second' then
      update public.prize_pool
      set second_prize_remaining = second_prize_remaining - 1,
          updated_at = now()
      where id = 1;
    else
      update public.prize_pool
      set third_prize_remaining = third_prize_remaining - 1,
          updated_at = now()
      where id = 1;
    end if;

    update public.spin_sessions
    set spin_count = spin_count + 1,
        has_won = true,
        prize_tier = v_prize_tier,
        updated_at = now()
    where session_id = p_session_id
    returning spin_count into v_spins_used;

    return jsonb_build_object(
      'status', 200,
      'result', 'win',
      'prizeTier', v_prize_tier,
      'spinsUsed', v_spins_used,
      'spinsRemaining', 0
    );
  end if;

  update public.spin_sessions
  set spin_count = spin_count + 1,
      updated_at = now()
  where session_id = p_session_id
  returning spin_count into v_spins_used;

  return jsonb_build_object(
    'status', 200,
    'result', 'no_win',
    'prizeTier', 'none',
    'spinsUsed', v_spins_used,
    'spinsRemaining', greatest(0, 3 - v_spins_used)
  );
end;
$$;
